2022-03-19 13:58:36,690 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:44]
2022-03-19 14:38:09,402 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:44]
2022-03-19 14:46:02,894 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:44]
2022-03-19 14:46:04,829 ERROR: Exception on /user/roman [GET] [in C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\roman\PycharmProjects\microblog\app\routes.py", line 99, in user
    return render_template('user.html', user=user, posts=posts)
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\roman\PycharmProjects\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\roman\PycharmProjects\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\roman\PycharmProjects\microblog\app\templates\user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-03-19 14:49:12,398 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:43]
2022-03-19 15:01:14,912 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:43]
2022-03-19 15:04:42,675 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:43]
2022-03-19 15:10:12,598 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:43]
2022-03-19 15:14:35,186 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:43]
2022-03-19 15:15:48,261 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:43]
2022-03-19 15:19:56,881 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:43]
2022-03-19 17:47:19,968 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:45]
2022-03-19 17:55:56,828 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:47]
2022-03-19 18:21:32,084 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:49]
2022-03-19 18:22:39,684 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:49]
2022-03-19 18:22:42,297 ERROR: Exception on /user/roman [GET] [in C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\roman\PycharmProjects\microblog\app\routes.py", line 138, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\roman\PycharmProjects\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\roman\PycharmProjects\microblog\app\templates\base.html", line 51, in template
    {% block content %}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '{'
2022-03-19 18:23:12,405 ERROR: Exception on / [GET] [in C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\roman\PycharmProjects\microblog\app\routes.py", line 37, in index
    return render_template('index.html', title='Home', form=form,
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\roman\PycharmProjects\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\roman\PycharmProjects\microblog\app\templates\base.html", line 51, in template
    {% block content %}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '{'
2022-03-19 18:24:12,939 ERROR: Exception on /login [POST] [in C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\roman\PycharmProjects\microblog\app\routes.py", line 63, in login
    if user is None or not user.check_password(form.password.data):
  File "C:\Users\roman\PycharmProjects\microblog\app\models.py", line 38, in check_password
    return check_password_hash(self.password_hash, password)
  File "C:\Users\roman\PycharmProjects\microblog\venv\lib\site-packages\werkzeug\security.py", line 215, in check_password_hash
    if pwhash.count("$") < 2:
AttributeError: 'NoneType' object has no attribute 'count'
2022-03-19 18:25:24,725 INFO: Microblog startup [in C:\Users\roman\PycharmProjects\microblog\app\__init__.py:49]
